---

environment:
  type: "object"
  required: true
  patternProperties:
      "^\\w+":
        "$ref": "#/properties/envs"
  additionalProperties: false

envs:
  type: "object"
  properties:
    username:
      description: "Username used to authenticate."
      type: "string"
      secret: false
      required: true
      default: "admin"
    password:
      description: "Password used to authenticate."
      type: "string"
      secret: true
      required: false
    enable:
      description: "Enable password."
      type: "string"
      secret: true
      required: false
      default: "password"
    b64password:
      description: "Password used to authenticate base64d."
      type: "string"
      secret: true
      required: false
    64enable:
      description: "Enable password base64d."
      type: "string"
      secret: true
      required: false
      default: "password"
    method:
      description: "Connection method."
      type: "string"
      secret: false
      default: "ssh"
      enum:
        - "ssh"
        - "telnet"
      required: true
